name: Build Executables with Nuitka

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-15-intel, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: gui_gslgen.py
          mode: standalone
          enable-plugins: pyside6
          windows-console-mode: disable
          mingw64: true
          windows-icon-from-ico: app_icon.ico
          macos-app-icon: app_icon.icns
          linux-icon: icon_256.png
          include-data-files: |
            app_icon.ico=app_icon.ico
            app_icon.icns=app_icon.icns
            icon_256.png=icon_256.png

      - name: Archive Build Folder
        shell: python
        run: |
          import shutil
          import os

          output_zip = 'GSL_Generator_${{ matrix.os }}'

          # Check if Nuitka created a macOS .app bundle or a standard .dist folder
          if os.path.exists('build/gui_gslgen.app'):
              shutil.make_archive(output_zip, 'zip', root_dir='build', base_dir='gui_gslgen.app')
          elif os.path.exists('build/gui_gslgen.dist'):
              shutil.make_archive(output_zip, 'zip', root_dir='build', base_dir='gui_gslgen.dist')
          else:
              print('Error: Build folder not found!')
              exit(1)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: GSL_Generator_${{ matrix.os }}.zip
